# Generated by Django 5.0.3 on 2024-03-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_auth', '0002_userprofile_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
