# Generated by Django 5.0.2 on 2024-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint')], default='suggestion', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='DefaultUsername', max_length=150),
        ),
    ]
