# Generated by Django 5.0.2 on 2024-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_alter_userprofile_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
